services:
  database:
    container_name: example_laravel_db
    image: mariadb:lts
    restart: always
    environment:
      - MARIADB_DATABASE=laravel
      - MARIADB_ROOT_PASSWORD=my-secret-pw
    networks:
      - example-laravel-network
    volumes:
      - db-storage:/var/lib/mysql

  webservice:
    container_name: example_laravel_webservice
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - '80:80'
    networks:
      - example-laravel-network
    volumes:
      - web-storage:/var/www/html/storage/app/public

networks:
    example-laravel-network:
        driver: bridge

volumes:
    web-storage: {}
    db-storage: {}

